apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: tp2
spec:
  type: ClusterIP  # Exposto apenas no cluster (padr√£o)
  ports:
  - port: 8081        # Porta do Service (outros PODs acessam por esta porta)
    targetPort: 80    # Porta do container nginx (para onde redireciona)
    protocol: TCP
  selector:
    app: nginx        # Seleciona PODs com label app=nginx

